import java.math.BigInteger;
import java.security.MessageDigest;
public class md5 {
    public static String getMd5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static void main(String args[]) {
        String s = "Sachin";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
    }
}